---
title: "BLB Tutorial"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{BLB Tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(devtools)
install_github("Arisina2309/BLB")
library(BLB)
```


```{r}
# Linear regression

n <- 1000 # Draws from X 
d <- 100 # Dimension of X
b = floor(n^(.7))
X <- matrix(0, nrow = n, ncol = d)
for(i in 1:d){
  X[,i] <- rt(n, 3) # T3 generation
}
Y <- X %*% rep(1,d) + rnorm(n,mean = 0, sd = 10) # Linear generation of Y
r <- 50 # number of Monte Carlo iterations
s <- 10 # number of sampled subsets
blb_linear_regression(X, Y, b, s, r)

# Quantile regression

n <- 1000 # Draws from X 
d <- 100 # Dimension of X
b = floor(n^(.7))
X <- matrix(0, nrow = n, ncol = d)
for(i in 1:d){
  X[,i] <- rt(n, 1) # T1/Cauchy generation
}
Y <- X %*% rep(1,d) + rnorm(n,mean = 0, sd = 10) # Linear generation of Y
r <- 50 # number of Monte Carlo iterations
s <- 10 # number of sampled subsets
q <- 0.9 # quantile for quantile regression
blb_quantile_regression(X, Y, b, s, r, q)
```

